# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 781)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startRecognize = QtWidgets.QPushButton(self.centralwidget)
        self.startRecognize.setGeometry(QtCore.QRect(460, 640, 151, 61))
        self.startRecognize.setObjectName("startRecognize")
        self.startDetect = QtWidgets.QPushButton(self.centralwidget)
        self.startDetect.setGeometry(QtCore.QRect(260, 640, 151, 61))
        self.startDetect.setObjectName("startDetect")
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(0, 0, 800, 600))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.videoLabel.setFont(font)
        self.videoLabel.setText("")
        self.videoLabel.setObjectName("videoLabel")
        self.detectedFace1 = QtWidgets.QLabel(self.centralwidget)
        self.detectedFace1.setGeometry(QtCore.QRect(840, 50, 112, 112))
        self.detectedFace1.setText("")
        self.detectedFace1.setObjectName("detectedFace1")
        self.similarFace1 = QtWidgets.QLabel(self.centralwidget)
        self.similarFace1.setGeometry(QtCore.QRect(830, 280, 112, 112))
        self.similarFace1.setText("")
        self.similarFace1.setObjectName("similarFace1")
        self.similarFace2 = QtWidgets.QLabel(self.centralwidget)
        self.similarFace2.setGeometry(QtCore.QRect(980, 280, 112, 112))
        self.similarFace2.setText("")
        self.similarFace2.setObjectName("similarFace2")
        self.similarFace3 = QtWidgets.QLabel(self.centralwidget)
        self.similarFace3.setGeometry(QtCore.QRect(980, 500, 112, 112))
        self.similarFace3.setText("")
        self.similarFace3.setObjectName("similarFace3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(840, 10, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(830, 230, 121, 16))
        self.label_2.setObjectName("label_2")
        self.detectedFace2 = QtWidgets.QLabel(self.centralwidget)
        self.detectedFace2.setGeometry(QtCore.QRect(980, 50, 112, 112))
        self.detectedFace2.setText("")
        self.detectedFace2.setObjectName("detectedFace2")
        self.inputFace = QtWidgets.QPushButton(self.centralwidget)
        self.inputFace.setGeometry(QtCore.QRect(650, 640, 151, 61))
        self.inputFace.setObjectName("inputFace")
        self.selectPhoto = QtWidgets.QPushButton(self.centralwidget)
        self.selectPhoto.setGeometry(QtCore.QRect(830, 640, 151, 61))
        self.selectPhoto.setObjectName("selectPhoto")
        self.openCamera = QtWidgets.QPushButton(self.centralwidget)
        self.openCamera.setGeometry(QtCore.QRect(40, 640, 151, 61))
        self.openCamera.setObjectName("openCamera")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1112, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startRecognize.setText(_translate("MainWindow", "开始识别"))
        self.startDetect.setText(_translate("MainWindow", "开始检测"))
        self.label.setText(_translate("MainWindow", "检测到的人脸："))
        self.label_2.setText(_translate("MainWindow", "相似的人脸："))
        self.inputFace.setText(_translate("MainWindow", "录入人脸"))
        self.selectPhoto.setText(_translate("MainWindow", "选择照片"))
        self.openCamera.setText(_translate("MainWindow", "打开摄像头"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.action.setText(_translate("MainWindow", "人脸录入"))
